spring.application.name=oasis-cinema-v2.

# Configuración de H2 con persistencia en archivo
# En Railway, esto guardará el archivo en el volumen del servidor
spring.datasource.url=jdbc:h2:file:~/data/oasis_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2 habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Habilita el acceso a la consola desde cualquier lugar (solo para pruebas)
spring.h2.console.settings.web-allow-others=true

# Actualización automática de tablas (CINE_USERS y MOVIE_ENTITY)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PUERTO DINÁMICO: Crucial para que Railway asigne el puerto correcto
server.port=${PORT:8080}

# Configuración para que Swagger no se pierda en Railway
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs