spring.application.name=oasis-cinema-v2

# --- CONEXIÓN AL VOLUMEN DE RAILWAY ---
# El punto "." es vital para que use la carpeta del proyecto vinculada al volumen
spring.datasource.url=jdbc:h2:file:./oasis_db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- CONSOLA H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# --- PERSISTENCIA DE TABLAS ---
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
springdoc.swagger-ui.path=/swagger-ui.html