
spring.application.name=oasis

# Configuración para usar H2 (Base de datos en memoria)
spring.datasource.url=jdbc:h2:file:~/data/oasis_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola para ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
